# https://byrdwell.com/Triacylglycerols/FattyAcids.htm

c4 =
    .common = Butyric
    .systematic = Butanoic
c5 =
    .common = Valeric
    .systematic = Pentanoic
c6 =
    .common = Caproic
    .systematic = Hexanoic
c7 =
    .common = Enanthic
    .systematic = Heptanoic
c8 =
    .common = Caprylic
    .systematic = Octanoic
c9 =
    .common = Pelargonic
    .systematic = Nonanoic
c10 =
    .common = Capric
    .systematic = Decanoic
c11 =
    .common = Undecylic
    .systematic = Hendecanoic
c12 =
    .common = Lauric
    .systematic = Dodecanoic
c13 =
    .common = Tridecylic
    .systematic = Tridecanoic
c14 =
    .common = Myristic
    .systematic = Tetradecanoic
c15 =
    .common = Pentadecylic
    .systematic = Pentadecanoic
c16 =
    .common = Palmitic
    .systematic = Hexadecanoic
c16c9 =
    .common = Palmitoleic
    .systematic = c-9-Hexadecenoic
c16t9 =
    .common = Palmitelaidic
    .systematic = t-9-Hexadecenoic
c17 =
    .common = Margaric
    .systematic = Heptadecanoic
c18 =
    .common = Stearic
    .systematic = Octadecanoic
c18c9 =
    .common = Oleic
    .systematic = c-9-Octadecenoic
c18t9 =
    .common = Elaidic
    .systematic = t-9-Octadecenoic
c18c6c9 =
    .common = γ-Linoleic
    .systematic = c-9,12-Octadecadienoic
c18c9c12 =
    .common = Linoleic
    .systematic = c-9,12-Octadecadienoic
c18c9c12c15 =
    .common = α-Linolenic
    .systematic = c-9,12,15-Octadecatrienoic
c18c6c9c12 =
    .common = γ-Linolenic
    .systematic = c-6,9,12-Octadecatrienoic
c18c9t11t13 =
    .common = α-Eleostearic
    .systematic = 9c,11t,13t-Octadecatrienoic
c18t9t11t13 =
    .common = β-Eleostearic
    .systematic = 9t,11t,13t-Octadecatrienoic
c18c8t10c12 =
    .common = Jacaric
    .systematic = 8c,10t,12c-Octadecatrienoic
c18t9t11c13 =
    .common = Catalpic
    .systematic = 9t,11t,13c-Octadecatrienoic
c18c6c9c12c15 =
    .common = Stearidonic
    .systematic = c-6,9,12,15-Octadecatetraenoic
c19 =
    .common = Nonadecylic
    .systematic = Nonadecanoic
c20 =
    .common = Arachidic
    .systematic = Eicosanoic
c20c9 =
    .common = Gadoleic
    .systematic = c-9-Eicosenoic
c20c11 =
    .common = Gondoic
    .systematic = c-11-Eicosenoic
c20c11c14 =
    .common = DihomoLinoleic
    .systematic = c-11,14-Eicosadienoic
c20c11c14c17 =
    .common = Bis-homo-α-Linolenic, ETA
    .systematic = c-11,14,17-Eicosatrienoic
c20c8c11c14 =
    .common = Bis-homo-γ-Linolenic
    .systematic = c-8,11,14-Eicosatrienoic
c20c5c8c11 =
    .common = Mead
    .systematic = c-5,8,11-Eicosatrienoic
c20c5c8c11c14 =
    .common = Arachidonic
    .systematic = c-5,8,11,14-Eicosatetraenoic
c20c8c11c14c17 =
    .common = Eicosatetraenoic
    .systematic = c-8,11,14,17-Eicosatetraenoic
c20c5c8c11c14c17 =
    .common = EPA
    .systematic = c-5,8,11,14,17-EicosaPentaenoic
c21 =
    .common = Heneicosylic
    .systematic = Heneicosanoic
c22 =
    .common = Behenic
    .systematic = Docosanoic
c22c13 =
    .common = Erucic
    .systematic = c-13-Docosenoic
c22c13c16 =
    .common = Docosadienoic
    .systematic = c-13,16-Docosadienoic
c22c5c13c16 =
    .common = Eranthic
    .systematic = c-5,13,16-Docosatrienoic
c22c7c10c13c16 =
    .common = Adrenic
    .systematic = c-7,10,13,16-Docosatetraenoic
c22c7c10c13c16c19 =
    .common = DPA
    .systematic = c-7,10,13,16,19-DocosaPentaenoic
c22c4c7c10c13c16c19 =
    .common = DHA
    .systematic = c-4,7,10,13,16,19-DocosaHexaenoic
c23 =
    .common = Tricosylic
    .systematic = Tricosanoic
c24 =
    .common = Lignoceric
    .systematic = Tetracosanoic
c24c15 =
    .common = Nervonic
    .systematic = c-15-Tetracosenoic
c24c15c18 =
    .common = Tetracosadienoic
    .systematic = c-15,18-Tetracosadienoic
c24c12c15c18 =
    .common = Tetracosatrienylic
    .systematic = c-12,15,18-Tetracosatrienoic
c24c9c12c15c18 =
    .common = Tetracosatetraenylic
    .systematic = c-9,12,15,18-Tetracosatetraenoic
c24c6c9c12c15c18 =
    .common = Tetracosapentaenylic
    .systematic = c-6,9,12,15,18-Tetracosapentaenoic
c24c6c9c12c15c18c21 =
    .common = Tetracosahexaenylic
    .systematic = c-6,9,12,15,18,21-Tetracosahexaenoic
c25 =
    .common = Hyenic
    .systematic = Pentacosanoic
c26 =
    .common = Cerotic
    .systematic = Hexacosanoic
c26c17 =
    .common = Ximenic
    .systematic = c-17-Hexacosenoic
c26u0u0 =
    .common = Hexacosadienylic
    .systematic = Hexacosadienoic
c26u0u0u0 =
    .common = Hexacosatrienylic
    .systematic = Hexacosatrienoic
c26u0u0u0u0 =
    .common = Hexacosatetraenylic
    .systematic = Hexacosatetraenoic
c26u0u0u0u0u0 =
    .common = Hexacosapentaenylic
    .systematic = Hexacosapentaenoic
c26u0u0u0u0u0u0 =
    .common = Hexacosahexaenylic
    .systematic = Hexacosahexaenoic
c27 =
    .common = Carboceric
    .systematic = Heptacosanoic
c28 =
    .common = Montanic
    .systematic = Octacosanoic
c28u0 =
    .common = Octacosenylic
    .systematic = Octacosenoic
c28u0u0 =
    .systematic = Octacosadienoic
c29 =
    .common = Nonacosylic
    .systematic = Nonacosanoic
c30 =
    .common = Melissic
    .systematic = Triacontanoic
c30c21 =
    .common = Lumequeic
    .systematic = c-21-Triacontenoic
c31 =
    .common = Henatriacontylic
    .systematic = Henatriacontanoic
c32 =
    .common = Lacceroic
    .systematic = Dotriacontanoic
c32u0 =
    .common = Dotriacontenylic
    .systematic = Dotriacontenoic
c32u0u0 =
    .systematic = Dotriacontadienoic
c33 =
    .common = Psyllic
    .systematic = Triatriacontanoic
c34 =
    .common = Gheddic
    .systematic = Tetratriacontanoic
c34u0 =
    .common = Tetratriacontenylic
    .systematic = Tetratriacontenoic
c34u0u0 =
    .systematic = Tetratriacontadienoic
c35 =
    .common = Ceroplastic
    .systematic = Pentatriacontanoic
c36 =
    .common = Hexatriacontylic
    .systematic = Hexatriacontanoic
c36u0 =
    .common = Hexatriacontenylic
    .systematic = Hexatriacontenoic
c36u0u0 = =
    .systematic = Hexatriacontadienoic