# IPPRAS

[c4]
abbreviation = ["Bu"]
common_name = ["Butyric acid"]
systematic_name = "Butanoic acid"

[c5]
abbreviation = ["V"]
common_name = ["Valeric acid"]
systematic_name = "Pentanoic acid"

[c6]
abbreviation = ["Co"]
common_name = ["Caproic acid"]
systematic_name = "Hexanoic acid"

[c7]
abbreviation = ["En"]
common_name = ["Enanthic acid"]
systematic_name = "Heptanoic acid"

[c8]
abbreviation = ["Cy"]
common_name = ["Caprylic acid"]
systematic_name = "Octanoic acid"

[c9]
common_name = ["Pelargonic acid"]
systematic_name = "Nonanoic acid"

[c10]
abbreviation = ["Ca"]
common_name = ["Capric acid"]
systematic_name = "Decanoic acid"

[c11]
common_name = ["Undecylic acid"]
systematic_name = "Hendecanoic acid"

[c12]
abbreviation = ["La"]
common_name = ["Lauric acid"]
systematic_name = "Dodecanoic acid"

[c13]
common_name = ["Tridecylic acid"]
systematic_name = "Tridecanoic acid"

[c14]
abbreviation = ["M"]
common_name = ["Myristic acid"]
systematic_name = "Tetradecanoic acid"

[c15]
common_name = ["Pentadecylic acid"]
systematic_name = "Pentadecanoic acid"

[c16]
abbreviation = ["P"]
common_name = ["Palmitic acid"]
systematic_name = "Hexadecanoic acid"

[c16c9]
abbreviation = ["Po"]
common_name = ["Palmitoleic acid"]
systematic_name = "c-9-Hexadecenoic acid"

[c16t9]
abbreviation = ["Pe"]
common_name = ["Palmitelaidic acid"]
systematic_name = "t-9-Hexadecenoic acid"

[c17]
common_name = ["Margaric acid"]
systematic_name = "Heptadecanoic acid"

[c18]
abbreviation = ["S"]
common_name = ["Stearic acid"]
systematic_name = "Octadecanoic acid"

[c18c9]
abbreviation = ["O"]
common_name = ["Oleic acid"]
systematic_name = "c-9-Octadecenoic acid"

[c18t9]
abbreviation = ["El"]
common_name = ["Elaidic acid"]
systematic_name = "t-9-Octadecenoic acid"

[c18c9c12]
abbreviation = ["L"]
common_name = ["Linoleic acid"]
systematic_name = "c-9,12-Octadecadienoic acid"

[c18c9c12c15]
abbreviation = ["α-Ln"]
common_name = ["α-Linolenic acid"]
systematic_name = "c-9,12,15-Octadecatrienoic acid"

[c18c6c9c12]
abbreviation = ["GLA", "γ-Ln"]
common_name = ["γ-Linolenic acid"]
systematic_name = "c-6,9,12-Octadecatrienoic acid"

[c18c9t11t13]
abbreviation = ["Eo"]
common_name = ["α-Eleostearic acid"]
systematic_name = "9c,11t,13t-Octadecatrienoic acid"

[c18t9t11t13]
common_name = ["β-Eleostearic acid"]
systematic_name = "9t,11t,13t-Octadecatrienoic acid"

[c18c8t10c12]
abbreviation = ["Ja"]
common_name = ["Jacaric acid"]
systematic_name = "8c,10t,12c-Octadecatrienoic acid"

[c18t9t11c13]
abbreviation = ["Ct"]
common_name = ["Catalpic acid"]
systematic_name = "9t,11t,13c-Octadecatrienoic acid"

[c18c6c9c12c15]
abbreviation = ["St"]
common_name = ["Stearidonic acid"]
systematic_name = "c-6,9,12,15-Octadecatetraenoic acid"

[c19]
common_name = ["Nonadecylic acid"]
systematic_name = "Nonadecanoic acid"

[c20]
abbreviation = ["A"]
common_name = ["Arachidic acid"]
systematic_name = "Eicosanoic acid"

[c20c9]
abbreviation = ["G"]
common_name = ["Gadoleic acid"]
systematic_name = "c-9-Eicosenoic acid"

[c20c11]
abbreviation = ["Go"]
common_name = ["Gondoic acid"]
systematic_name = "c-11-Eicosenoic acid"

[c20c11c14]
common_name = ["DihomoLinoleic acid"]
systematic_name = "c-11,14-Eicosadienoic acid"

[c20c11c14c17]
common_name = ["Bis-homo-α-Linolenic acid, ETA"]
systematic_name = "c-11,14,17-Eicosatrienoic acid"

[c20c8c11c14]
common_name = ["Bis-homo-γ-Linolenic acid"]
systematic_name = "c-8,11,14-Eicosatrienoic acid"

[c20c5c8c11]
common_name = ["Mead acid"]
systematic_name = "c-5,8,11-Eicosatrienoic acid"

[c20c5c8c11c14]
abbreviation = ["Ao"]
common_name = ["Arachidonic acid"]
systematic_name = "c-5,8,11,14-Eicosatetraenoic acid"

[c20c8c11c14c17]
common_name = ["Eicosatetraenoic acid"]
systematic_name = "c-8,11,14,17-Eicosatetraenoic acid"

[c20c5c8c11c14c17]
abbreviation = ["Ep"]
common_name = ["EPA"]
systematic_name = "c-5,8,11,14,17-EicosaPentaenoic acid"

[c21]
common_name = ["Heneicosylic acid"]
systematic_name = "Heneicosanoic acid"

[c22]
abbreviation = ["B"]
common_name = ["Behenic acid"]
systematic_name = "Docosanoic acid"

[c22c13]
abbreviation = ["E"]
common_name = ["Erucic acid"]
systematic_name = "c-13-Docosenoic acid"

[c22c13c16]
common_name = ["Docosadienoic acid"]
systematic_name = "c-13,16-Docosadienoic acid"

[c22c5c13c16]
common_name = ["Eranthic acid"]
systematic_name = "c-5,13,16-Docosatrienoic acid"

[c22c7c10c13c16]
common_name = ["Adrenic acid"]
systematic_name = "c-7,10,13,16-Docosatetraenoic acid"

[c22c7c10c13c16c19]
abbreviation = ["Dp"]
common_name = ["DPA"]
systematic_name = "c-7,10,13,16,19-DocosaPentaenoic acid"

[c22c4c7c10c13c16c19]
abbreviation = ["Dh"]
common_name = ["DHA"]
systematic_name = "c-4,7,10,13,16,19-DocosaHexaenoic acid"

[c23]
common_name = ["Tricosylic acid"]
systematic_name = "Tricosanoic acid"

[c24]
abbreviation = ["Lg"]
common_name = ["Lignoceric acid"]
systematic_name = "Tetracosanoic acid"

[c24c15]
abbreviation = ["N"]
common_name = ["Nervonic acid"]
systematic_name = "c-15-Tetracosenoic acid"

[c24c15c18]
common_name = ["Tetracosadienoic acid"]
systematic_name = "c-15,18-Tetracosadienoic acid"

[c24c12c15c18]
common_name = ["Tetracosatrienylic acid"]
systematic_name = "c-12,15,18-Tetracosatrienoic acid"

[c24c9c12c15c18]
common_name = ["Tetracosatetraenylic acid"]
systematic_name = "c-9,12,15,18-Tetracosatetraenoic acid"

[c24c6c9c12c15c18]
common_name = ["Tetracosapentaenylic acid"]
systematic_name = "c-6,9,12,15,18-Tetracosapentaenoic acid"

[c24c6c9c12c15c18c21]
common_name = ["Tetracosahexaenylic acid"]
systematic_name = "c-6,9,12,15,18,21-Tetracosahexaenoic acid"

[c25]
common_name = ["Hyenic acid"]
systematic_name = "Pentacosanoic acid"

[c26]
abbreviation = ["Ce"]
common_name = ["Cerotic acid"]
systematic_name = "Hexacosanoic acid"

[c26c17]
abbreviation = ["Xi"]
common_name = ["Ximenic acid"]
systematic_name = "c-17-Hexacosenoic acid"

[c26u0u0]
common_name = ["Hexacosadienylic acid"]
systematic_name = "Hexacosadienoic acid"

[c26u0u0u0]
common_name = ["Hexacosatrienylic acid"]
systematic_name = "Hexacosatrienoic acid"

[c26u0u0u0u0]
common_name = ["Hexacosatetraenylic acid"]
systematic_name = "Hexacosatetraenoic acid"

[c26u0u0u0u0u0]
common_name = ["Hexacosapentaenylic acid"]
systematic_name = "Hexacosapentaenoic acid"

[c26u0u0u0u0u0u0]
common_name = ["Hexacosahexaenylic acid"]
systematic_name = "Hexacosahexaenoic acid"

[c27]
common_name = ["Carboceric acid"]
systematic_name = "Heptacosanoic acid"

[c28]
abbreviation = ["Mo"]
common_name = ["Montanic acid"]
systematic_name = "Octacosanoic acid"

[c28u0]
common_name = ["Octacosenylic acid"]
systematic_name = "Octacosenoic acid"

[c28u0u0]
systematic_name = "Octacosadienoic acid"

[c29]
common_name = ["Nonacosylic acid"]
systematic_name = "Nonacosanoic acid"

[c30]
common_name = ["Melissic acid"]
systematic_name = "Triacontanoic acid"

[c30c21]
common_name = ["Lumequeic acid"]
systematic_name = "c-21-Triacontenoic acid"

[c31]
common_name = ["Henatriacontylic acid"]
systematic_name = "Henatriacontanoic acid"

[c32]
common_name = ["Lacceroic acid"]
systematic_name = "Dotriacontanoic acid"

[c32u0]
common_name = ["Dotriacontenylic acid"]
systematic_name = "Dotriacontenoic acid"

[c32u0u0]
systematic_name = "Dotriacontadienoic acid"

[c33]
common_name = ["Psyllic acid"]
systematic_name = "Triatriacontanoic acid"

[c34]
common_name = ["Gheddic acid"]
systematic_name = "Tetratriacontanoic acid"

[c34u0]
common_name = ["Tetratriacontenylic acid"]
systematic_name = "Tetratriacontenoic acid"

[c34u0u0]
systematic_name = "Tetratriacontadienoic acid"

[c35]
common_name = ["Ceroplastic acid"]
systematic_name = "Pentatriacontanoic acid"

[c36]
common_name = ["Hexatriacontylic acid"]
systematic_name = "Hexatriacontanoic acid"

[c36u0]
common_name = ["Hexatriacontenylic acid"]
systematic_name = "Hexatriacontenoic acid"

[c36u0u0]
systematic_name = "Hexatriacontadienoic acid"
