= UTCA

image:https://img.shields.io/github/v/release/ippras/utca-source?label=Version&sort=semver[Version]
image:https://img.shields.io/github/license/ippras/utca-source?label=License[License, link=license]
image:https://img.shields.io/github/actions/workflow/status/ippras/utca-source/rust.yml?logo=github&label=Rust[Rust, link=https://github.com/ippras/utca-source/actions/workflows/rust.yml]
image:https://img.shields.io/github/actions/workflow/status/ippras/utca-source/pages.yml?logo=github&label=Github Pages[Github Pages, link=https://github.com/ippras/utca-source/actions/workflows/pages.yml]

Ultimate Triacylglycerol Calculation Application

== Documentation

|===
|link:doc/en-US.adoc[English 🇺🇸] | link:doc/ru-RU.adoc[Русский 🇷🇺]
|===

== Run

=== Native

`cargo run`

=== Web (http://127.0.0.1:8080)

`trunk serve --release --filehash=false`

==== Requirements

`rustup target add wasm32-unknown-unknown`

==== Errors

integrity:

* `chrome://settings/clearBrowserData`
* `Дополнительные`
* `Изображения и другие файлы, сохраненные в кеше`
* `Удалить данные`

== See Also

* https://byrdwell.com/Triacylglycerols/TAGbyMass1.htm[byrdwell.com]
* https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl[nist.gov, title=Atomic Weights and Isotopic Compositions for All Elements]

== Dedication

== TODO

Стандарт – отвязка от единственной реализации.
Если у него одна распространённая реализация, и нет заинтересованных (обычно это достаточно крупные конторы на рынке компиляторов), то никто не будет настаивать на стандартизации и организовывать работу комитета по разработке этого стандарта.
Стандартизация нужна там где есть несколько независимых поставщиков компиляторов. В случае с одной реализацией языка в этом нет смысла, т.к. эта реализация и есть стандарт де-факто
Rust и Haskell, где есть RFC, описывающие желаемое поведение;
Те языки у которых есть стандарт, этот самый стандарт появился по историческим причинам - из-за распространённости нескольких конкурирующих реализаций, каждая из которых ещё и расширениями была обвешена.
наличие того самого ИСО на кресты, благодаря которому(в том числе) есть llvm
зачастую достаточно «спецификаций
