[formatting]
reorder_arrays = false
reorder_keys = true

# https://doc.rust-lang.org/cargo/reference/manifest.html
[[rule]]
formatting = { reorder_arrays = true, reorder_keys = true }
include = ["**/Cargo.toml"]

[[rule]]
formatting = { reorder_keys = false }
include = ["**/Cargo.toml"]
keys = ["package"]
