Composition-Mass-Nonstereospecific = Mass, mono
    .abbreviation = MMC
    .hover = Mass non-stereospecific composition
Composition-Mass-Stereospecific = Mass, stereo
    .abbreviation = MSC
    .hover = Mass stereospecific composition (agregation)
Composition-EquivalentCarbonNumber-Nonstereospecific = ECN, mono
    .abbreviation = NMC
    .hover = Equivalent carbon number non-stereospecific composition (agregation)
Composition-EquivalentCarbonNumber-Stereospecific = ECN, stereo
    .abbreviation = NSC
    .hover = Equivalent carbon number stereospecific composition
Composition-Species-Nonstereospecific = Species, mono
    .abbreviation = SMC
    .hover = Species non-stereospecific composition (permutation)
Composition-Species-Positionalspecific = Species, positional
    .abbreviation = SPC
    .hover = Species positional specific composition (permutation)
Composition-Species-Stereospecific = Species, stereo
    .abbreviation = SSC
    .hover = Species stereospecific composition
Composition-Type-Nonstereospecific = Type, mono
    .abbreviation = TMC
    .hover = Type non-stereospecific composition (permutation)
Composition-Type-Positionalspecific = Type, positional
    .abbreviation = TPC
    .hover = Type positional specific composition (permutation)
Composition-Type-Stereospecific = Type, stereo
    .abbreviation = TSC
    .hover = Type stereospecific composition
Composition-Unsaturation-Nonstereospecific = Unsaturation, mono
    .abbreviation = UMC
    .hover = Unsaturation non-stereospecific composition (agregation)
Composition-Unsaturation-Stereospecific = Unsaturation, stereo
    .abbreviation = USC
    .hover = Unsaturation stereospecific composition
