mass_nonstereospecific_composition = Mass, mono
    .abbreviation = MMC
    .hover = Mass non-stereospecific composition
mass_stereospecific_composition = Mass, stereo
    .abbreviation = MSC
    .hover = Mass stereospecific composition (agregation)
equivalent_carbon_number_nonstereospecific_composition = ECN, mono
    .abbreviation = NMC
    .hover = Equivalent carbon number non-stereospecific composition (agregation)
equivalent_carbon_number_stereospecific_composition = ECN, stereo
    .abbreviation = NSC
    .hover = Equivalent carbon number stereospecific composition
species_nonstereospecific_composition = Species, mono
    .abbreviation = SMC
    .hover = Species non-stereospecific composition (permutation)
species_positionalspecific_composition = Species, positional
    .abbreviation = SPC
    .hover = Species positional specific composition (permutation)
species_stereospecific_composition = Species, stereo
    .abbreviation = SSC
    .hover = Species stereospecific composition
type_nonstereospecific_composition = Type, mono
    .abbreviation = TMC
    .hover = Type non-stereospecific composition (permutation)
type_positionalspecific_composition = Type, positional
    .abbreviation = TPC
    .hover = Type positional specific composition (permutation)
type_stereospecific_composition = Type, stereo
    .abbreviation = TSC
    .hover = Type stereospecific composition
unsaturation_nonstereospecific_composition = Unsaturation, mono
    .abbreviation = UMC
    .hover = Unsaturation non-stereospecific composition (agregation)
unsaturation_stereospecific_composition = Unsaturation, stereo
    .abbreviation = USC
    .hover = Unsaturation stereospecific composition
