Indices_Monounsaturated = Monounsaturated
    .abbreviation = MUFA
    .hover = Sum of monounsaturated fatty acids.
Indices_Polyunsaturated = Polyunsaturated
    .abbreviation = PUFA
    .hover = Sum of polyunsaturated fatty acids.
Indices_Saturated = Saturated
    .abbreviation = SFA
    .hover = Sum of saturated fatty acids.
Indices_Trans = Trans
    .abbreviation = TFA
    .hover = Sum of trans fatty acids.
Indices_Unsaturated = Unsaturated
    .abbreviation = UFA
    .hover = Sum of unsaturated fatty acids.
Indices_Unsaturated-9 = Omega -9
Indices_Unsaturated-6 = Omega -6
Indices_Unsaturated-3 = Omega -3
Indices_Unsaturated9 = Delta 9
Indices_EicosapentaenoicAndDocosahexaenoic = Eicosapentaenoic and Docosahexaenoic
    .hover = Sum of Eicosapentaenoic and Docosahexaenoic.
Indices_FishLipidQuality = Fish Lipid Quality
    .abbreviation = FLQ
    .hover = Fish Lipid Quality.
Indices_HealthPromotingIndex = Health Promoting Index
    .abbreviation = HPI
    .hover = Health Promoting Index.
Indices_HypocholesterolemicToHypercholesterolemic = Hypocholesterolemic to Hypercholesterolemic
    .abbreviation = H/H
    .hover = Hypocholesterolemic to Hypercholesterolemic.
Indices_IndexOfAtherogenicity = Index of Atherogenicity
    .abbreviation = IA
    .hover = Index of Atherogenicity.
Indices_IndexOfThrombogenicity = Index of Thrombogenicity
    .abbreviation = IT
    .hover = Index of Thrombogenicity.
Indices_LinoleicToAlphaLinolenic = Linoleic to αLinolenic
    .abbreviation = LA/ALA
    .hover = Linoleic to αLinolenic.
Indices_Polyunsaturated-6ToPolyunsaturated-3 = Polyunsaturated -6 to Polyunsaturated -3
    .abbreviation = PUFA-6/PUFA-3
    .hover = Polyunsaturated -6 to Polyunsaturated -3.
Indices_PolyunsaturatedToSaturated = Polyunsaturated to Saturated
    .abbreviation = PUFA/SFA
    .hover = Polyunsaturated to Saturated.
Indices_UnsaturationIndex = Unsaturation Index
    .abbreviation = UI
    .hover = Unsaturation Index.

Indices_IodineValue = Iodine value
    .abbreviation = IV
    .hover = Iodine value
    .doi = { $Source ->
        *[Aocs] [AOCS recommended practice Cd 1c-85](https://library.aocs.org/Cd-1c-85/1)
        [Wang2012] [Wang et al. (2012)](https://doi.org/10.1016/S1872-5813(12)60018-8)
    }
CetaneNumber = Cetane number
    .abbreviation = CN
    .hover = Cetane number
    .doi = [Wang et al. (2012)](https://doi.org/10.1016/S1872-5813(12)60018-8)
OxidativeStability = Oxidative stability
    .abbreviation = OS
    .hover = Oxidative stability.
    .doi = [Wang et al. (2012)](https://doi.org/10.1016/S1872-5813(12)60018-8)
LongChainSaturatedFactor = Long Chain Saturated factor
    .abbreviation = LCSF
    .hover = Long Chain Saturated factor.
    .doi = [Ramos et al. (2009)](https://doi.org/10.1016/j.biortech.2008.06.039)
ColdFilterPluggingPoint = Cold filter plugging point
    .abbreviation = CFPP
    .hover = Cold filter plugging point.
    .doi = [Wang et al. (2012)](https://doi.org/10.1016/S1872-5813(12)60018-8)
